kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: database
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: database
        project: expense
    spec:
      containers:
      - name: mysql
        image: durga98/mysql:1.0.0
